[General]
auto-start = "Startup"
update-on-startup = true
zoom-path = "%appdata%/Zoom/bin/zoom.exe"

[Joining]
auto-join = true
offset = 00:00:30

[Syncing]
calendars = [ "*"]
period = 00:10:00
range-to-sync = 00:15:00

[Settings]
open-in-notepad = true